version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    ports:
      - "5433:5432"

  lunch_service:
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      NAME: ${NAME}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: "postgres-db"
      PORT: ${PORT}
    volumes:
      - static_volume:/docker_lunch_service/static

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - lunch_service

volumes:
  static_volume: